### ISSUE TITLE
Error retrieving IAM policy for storage bucket "b/artifacts.<project_id>.appspot.com"

### ISSUE THREAD

**Issue by 0x57696c6c** [SygniaLabs/ScallOps#23]
Using branch v0,4 as the master branch is returning even more errors during the terraform build (terraform v1.2.6).
I'm starting with a brand new GCP project, and enabled GCE, k8s, storage, containers, and secrets. 
Configured config.tfvars to include my project_id, infra_name, and backups_bucket_name,
Authenticated using the gcloud cli.
Initialized terraform and ran terraform apply --var-file=./config.tfvars.
Service accounts are created, the gitlab vm is started, the k8s cluster is created with nodes, storage bucket created, firewall rules in place. 
However, towards the end of the terraform build I constantly receive the following error:

```
Error: Error retrieving IAM policy for storage bucket "b/artifacts.<project_id>.appspot.com": googleapi: Error 404: The specified bucket does not exist., notFound

 with google_storage_bucket_iam_member.containeradmin_member, on iam.tf line 88, in resource "google_storage_bucket_iam_member" "containeradmin_member": 88: resource "google_storage_bucket_iam_member" "containeradmin_member" {
```

**Comment by gilb1** [comment]
Can you try enabling the Container Registry API and upload at least one container image to there?
https://console.cloud.google.com/marketplace/product/google/containerregistry.googleapis.com
https://console.cloud.google.com/gcr/images/<PROJECT-ID>

Let me know if it works for you, so I will add it to the README or code.
See also my full response here: https://github.com/SygniaLabs/ScallOps/issues/24
